### ISSUE TITLE
/metadata/tag-suggest

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#122]
hello,

i receive empty suggest.

```
{
  "errors": [],
  "suggestions": []
}
```

here is my config
```
# heroic.yaml
port: 8080

cluster:
  tags:
    site: nrtb
  protocols:
    - type: grpc
  discovery:
    type: static
    nodes:
      - "grpc://localhost"
      
metrics:
  backends:
    - type: datastax
      seeds:
        - cassandra
        
metadata:
  backends:
    - type: elasticsearch
      connection:
        clusterName: elasticsearch
        seeds:
          - elasticsearch
        index:                                                                                                                                                
          type: rotating                                                                                                                                      
          pattern: metadata-%s                                                                                                                                
          interval: 1w    
          
suggest:
  backends:
    - type: elasticsearch
      connection:
        clusterName: elasticsearch
        seeds:
          - elasticsearch
        index:                                                                                                                                                
          type: rotating                                                                                                                                      
          pattern: metadata-%s                                                                                                                                
          interval: 1w    
          
consumers:
  - type: kafka
    schema: com.spotify.heroic.consumer.schemas.Spotify100
    topics:
      - "metrics"
    config:
      group.id: heroic-consumer
      zookeeper.connect: kafka
      auto.offset.reset: smallest
      auto.commit.enable: true         
```
for elasticsearch i did 

```
script.inline: on
script.indexed: on
```

but i have no template inside
