### ISSUE TITLE
ERROR com.spotify.heroic.cluster.CoreClusterManager - 00000000 [failed] grpc://localhost

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#139]
when i start for the first time i get this error:

```08:16:27.286 [nioEventLoopGroup-2-1] WARN  io.netty.handler.codec.http2.Http2ConnectionHandler - [id: 0x7e246a6a] Sending GOAWAY failed: lastStreamId '0', errorCode '2', debugData 'Connection refused: localhost/127.0.0.1:0'. Forcing shutdown of the connection.
30/11/2016 09:16:27java.nio.channels.ClosedChannelException
30/11/2016 09:16:2708:16:27.298 [nioEventLoopGroup-2-2] ERROR com.spotify.heroic.cluster.CoreClusterManager - 00000000 [failed] grpc://localhost
30/11/2016 09:16:27java.lang.RuntimeException: Request finished with status code (Status{code=UNAVAILABLE, description=Transport closed for unknown reason, cause=null})
30/11/2016 09:16:27	at com.spotify.heroic.rpc.grpc.GrpcRpcClient$1.onClose(GrpcRpcClient.java:103)
30/11/2016 09:16:27	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:462)
30/11/2016 09:16:27	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:54)
30/11/2016 09:16:27	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
30/11/2016 09:16:27	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
30/11/2016 09:16:27	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
30/11/2016 09:16:27	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
30/11/2016 09:16:27	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
30/11/2016 09:16:27	at java.lang.Thread.run(Thread.java:745)
```

i have this config:
```
# heroic.yaml
port: 8080

cluster:
  tags:
    site: nsadb
  protocols:
    - type: grpc
  discovery:
    type: static
    nodes:
      - "grpc://localhost"
      
metrics:
  backends:
    - type: datastax
      seeds:
        - cassandra
        
metadata:
  backends:
    - type: elasticsearch
      writesPerSecond: 0
      connection:
        clusterName: elasticsearch
        seeds:
          - elasticsearch
        index:                                                                                                                                                
          type: single                                                                                                                                    
          index: metadata    
          
suggest:
  backends:
    - type: elasticsearch
      connection:
        clusterName: elasticsearch
        seeds:
          - elasticsearch
        index:                                                                                                                                                
          type: single                                                                                                                                    
          index: metadata 
```

**Comment by valentinul** [comment]
Hi,

I'm seeing the same issues with cluster settings. Also the same when using multiple nodes.
No idea on how to fix them yet.

**Comment by udoprog** [comment]
It seems like the grpc module doesn't have a default port, as seen here:
https://github.com/spotify/heroic/blob/master/rpc/grpc/src/main/java/com/spotify/heroic/rpc/grpc/GrpcRpcProtocolModule.java#L50

This will cause it to bind to a random port, not sure what happens on the client side to be honest.

**Comment by udoprog** [comment]
As a temporary workaround, you can configure the port to use like this:

```yaml
cluster:
  tags:
    site: nsadb
  protocols:
    - type: grpc
      port: 1394
  discovery:
    type: static
    nodes:
      - grpc://localhost:1394
```
