### ISSUE TITLE
How to cluster heroic

### ISSUE THREAD

**Issue by valentinul** [spotify/heroic#142]
Hi,

I'm trying to make an heroic cluster made out of 4 servers. I've looked into the docs but they seem to be outdated. 

Any idea on how to add nodes ?

Thank you

**Comment by udoprog** [comment]
Hey, we found an issue with #139 - the grpc module doesn't have a default port. We'll add that and the example configuration should work.

When it does, you should just be able to add more nodes under the list of nodes under the cluster configuration, as described here:
http://spotify.github.io/heroic/#!/docs/config/cluster

**Comment by valentinul** [comment]
Fixed

**Comment by mykolasmith** [comment]
Can someone post their cluster configuration? We're having trouble communicating between api and data nodes. Specifically, we're looking to have 3 API nodes and 1 data node in a cluster. The examples only seem to cover single node clusters with the metadata service running locally.

**Comment by valentinul** [comment]
Hi,

Sure. Here is my config.

```
# heroic.yaml
port: 8080

cluster:
  tags:
    site: HG
  protocols:
    - type: grpc
      port: 1394
  discovery:
    type: static
    nodes:
      - grpc://heroic.cc:1394
      - grpc://heroic1.cc:1394
      - grpc://heroic2.cc:1394
      - grpc://heroic3.cc:1394

metrics:
  backends:
    - type: datastax
      seeds:
        - cassandra-node1.cc
        - cassandra-node2.cc
        - cassandra-node3.cc
        - cassandra-node4.cc
        - cassandra-node5.cc

metadata:
  backends:
    - type: elasticsearch
      connection:
        index:
            type: rotating
            interval: 1d
        seeds:
            - "heroic-e.cc"
            - "heroic-e1.cc"
            - "heroic-e2.cc"
        clusterName: "heroic" 
        client: 
             type: transport
      backendType: kv 

suggest:
  backends:
    - type: elasticsearch
      connection:
        index:
            type: rotating
            interval: 1d
        seeds:
            - "heroic-e.cc"
            - "heroic-e1.cc"
            - "heroic-e2.cc"
        clusterName: "heroic" 
        client: 
             type: transport
      backendType: kv 

shellServer:
  host: "131.1.1.1"
  port: 9190
```
