### ISSUE TITLE
The cluster is consuming data but not returning anything anymore.

### ISSUE THREAD

**Issue by valentinul** [spotify/heroic#154]
Hi,
After deciding to go with a "cluster" because of the need of pushing more and more metrics, I cannot get back any data from the cluster. 
When I was running in single node mode, everything was returned as expected...

I'm using grafana as graphing engine and I have queries like the following:
`average by hosts from points(1d) where type=epp_connections with size=5m`

The same query executed in the shell server returns the following: 
```
heroic> query "average by hosts from points(1d) where type=epp_connections with size=5m"
LIMITS: []
TRACE:
com.spotify.heroic.CoreQueryManager#query (in 3.516us)
  grpc://heroic1.cc:1394#query (in 3.406us)
    com.spotify.heroic.metric.LocalMetricManager#query (in 2.522us)
time: 25.801 ms
```
Any ideas why ? 
My configuration is the following...

```
# heroic.yaml
port: 8080

consumers:
  - type: kafka
    schema: com.spotify.heroic.consumer.schemas.Spotify100
    topics:
      - "metrics"
    config:
      group.id: heroic
      zookeeper.connect: kafkabaer3.cc:2181,kafkabaer2.cc:2181,kafkabaer1.cc:2181
      auto.offset.reset: largest
      auto.commit.enable: true

cluster:
  tags:
    site: HG
  protocols:
    - type: grpc
      port: 1394
  discovery:
    type: static
    nodes:
      - grpc://heroic.cc:1394
      - grpc://heroic1.cc:1394
      - grpc://heroic2.cc:1394
      - grpc://heroic3.cc:1394
metrics:
  backends:
    - type: datastax
      seeds:
        - cassandra-node5.cc
        - cassandra-node2.cc
        - cassandra-node3.cc
        - cassandra-node4.cc
        - cassandra-node1.cc

metadata:
  backends:
    - type: elasticsearch
      backendType: kv
      connection:
        index:
            type: rotating 
            pattern: heroic-a-%s
            interval: 1d
        seeds:
            - heroic-e2.cc
            - heroic-e1.cc
            - heroic-e.cc
        clusterName: heroic
        nodeClient: true

suggest:
  backends:
    - type: elasticsearch
      backendType: kv
      connection:
        index:
            type: rotating
            pattern: heroic-a-%s
            interval: 1d
        seeds:
            - heroic-e2.cc
            - heroic-e1.cc
            - heroic-e.cc
        clusterName: heroic
        nodeClient: true

shellServer:
  host: "131.1.2.3"
  port: 9190
```
