### ISSUE TITLE
Restrict that a feature cannot be changed at query time

### ISSUE THREAD

**Issue by udoprog** [spotify/heroic#166]
Administrators might want to restrict that some features cannot be changed at query time.

As documented here: http://spotify.github.io/heroic/#!/docs/config/features

#### Suggestion

This suggestion is to allow these to be specified in the service configuration like the following:

```yaml
features:
  - "!-com.spotify.heroic.query_fanout"
```

**Comment by mykolasmith** [comment]
While we're at it, maybe update the documentation as well to show how one can disable features on a given node. We would like to disable `shift_range` by default. I imagine it works something like this?

```
cluster:
  features:
    - "-com.spotify.heroic.shift_range"
  protocols:
    - type: grpc
      host: 0.0.0.0
      port: 9698
  discovery:
    type: static
    nodes:
      - grpc://localhost:9698
```
