### ISSUE TITLE
Cassandra authentication and keyspace setting

### ISSUE THREAD

**Issue by deejay1** [spotify/heroic#17]
Currently there seems to be no way of specifying in the settings authentication credentials for the Cassandra DataStax backend and also you can't choose the keyspace to use or am I missing something?

Right now I worked around this issue by hardcoding both things in datastax/ManagedSetupConnection.java.

**Comment by udoprog** [comment]
Hey.

Looks like you are right. It's currently not supported. Should be easy enough to add. I'll mark it as an enhancement for now.

**Comment by udoprog** [comment]
Using this, it should be possible to configure authentication:
```yaml
type: datastax
authentication:
  type: plain
  username: username
  password: password
```

Please try it out, and tell me how it goes!

**Comment by deejay1** [comment]
Thanks, works now if I manually create the tables in Cassandra. Otherwise (with
```yaml
- type: datastax
  ---
  configure: true
```
I get 
```java
14:12:12.277 [main] ERROR com.spotify.heroic.HeroicService - Failed to start heroic
java.util.concurrent.ExecutionException: java.lang.Exception: 1 exception(s) caught: User heroic_user has no CREATE permission on <all keyspaces> or any of its parents
```
