### ISSUE TITLE
metrics/query elasticsearch error log : Failed to execute query phase

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#195]
hello ,

I always get this error and query are very slow

```
[DEBUG][action.search.type       ] [master] [25] Failed to execute query phase
17/01/2017 15:22:53org.elasticsearch.search.SearchContextMissingException: No search context found for id [25]
17/01/2017 15:22:53	at org.elasticsearch.search.SearchService.findContext(SearchService.java:537)
17/01/2017 15:22:53	at org.elasticsearch.search.SearchService.executeScan(SearchService.java:265)
17/01/2017 15:22:53	at org.elasticsearch.search.action.SearchServiceTransportAction$21.call(SearchServiceTransportAction.java:520)
17/01/2017 15:22:53	at org.elasticsearch.search.action.SearchServiceTransportAction$21.call(SearchServiceTransportAction.java:517)
17/01/2017 15:22:53	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
17/01/2017 15:22:53	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
17/01/2017 15:22:53	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
17/01/2017 15:22:53	at java.lang.Thread.run(Thread.java:745)
```

# heroic.yaml
```
port: 8080

cluster:
  tags:
    site: rsdb
  protocols:
    - type: grpc
      port: 1394
  discovery:
    type: static
    nodes:
      - grpc://localhost:1394
      - grpc://heroic-read:1394

      
metrics:
  backends:
    - type: datastax
      seeds:
        - cassandra
  fetchParallelism: 20000000
  seriesLimit: null
  aggregationLimit: null
  groupLimit: null
  dataLimit: null
  
metadata:
  backends:
    - type: elasticsearch
      writesPerSecond: 0
      connection:
        clusterName: elasticsearch
        seeds:
          - master
        index:                                                                                                                                                
          type: single                                                                                                                                    
          index: metadata    
          
suggest:
  backends:
    - type: elasticsearch
      connection:
        clusterName: elasticsearch
        seeds:
          - master
        index:                                                                                                                                                
          type: single                                                                                                                                    
          index: metadata 
```

I don't know how to fix it
any help would be appriciate

thanks
Lucile
