### ISSUE TITLE
Tag Equals and StartsLike fails to return results

### ISSUE THREAD

**Issue by dbrounst** [spotify/heroic#46]
If you could point me to where I have gone wrong or where in the code a mistake may have been made, it would be appreciated. 

I have done the following:
* curl -s -H "Content-Type: application/json" http://localhost:8080/write -d '{"series": {"key": "foo", "tags": {"host": "www.london.com","site":"lon"}}, "data": {"type": "points", "data": [[1463605960000, 46.0], [1463605970000, 69.0]]}}'
* curl -s -H "Content-Type: application/json" http://localhost:8080/write -d '{"series": {"key": "foo", "tags": {"host": "www.petaluma1.com","site":"pet"}}, "data": {"type": "points", "data": [[1463605960000, 46.0], [1463605970000, 69.0]]}}'
* curl -s -H "Content-Type: application/json" http://localhost:8080/write -d '{"series": {"key": "foo", "tags": {"host": "www.petaluma2.com","site":"pet"}}, "data": {"type": "points", "data": [[1463605960000, 46.0], [1463605970000, 69.0]]}}'

Successfully retrieved results:
* curl -H "Content-Type: application/json" http://localhost:8080/query/metrics -d '{"range": {"type": "relative", "unit": "HOURS", "value": 2}, "filter": ["key", "foo"]}'

Failed to retrieved results (equals):
* curl -H "Content-Type: application/json" http://localhost:8080/query/metrics -d '{"range": {"type": "relative", "unit": "HOURS", "value": 3}, "filter": ["and",["key", "foo"],["=","site", "pet"]]}'

Failed to retrieved results (starts like):
* curl -H "Content-Type: application/json" http://localhost:8080/query/metrics -d '{"range": {"type": "relative", "unit": "HOURS", "value": 3}, "filter": ["and",["key", "foo"],["^","site", "p"]]}'

**Comment by udoprog** [comment]
Hey,

Can you paste or describe the configuration you are using and which commit of Heroic you are running?

**Comment by dbrounst** [comment]
I am using the latest master branch.  Here is my yaml

**Comment by udoprog** [comment]
Hey,

With the configuraiton you gave me, I get an error when trying to start Heroic.

An Elasticsearch configuration that does what you want should look like this:

```
metadata:                                                                                                                                                     
  backends:                                                                                                                                                   
    - type: elasticsearch                                                                                                                                     
      connection:                                                                                                                                             
        clusterName: BP2                                                                                                                                      
        seeds:                                                                                                                                                
          - elasticsearchclient                                                                                                                               
        index:                                                                                                                                                
          type: rotating                                                                                                                                      
          pattern: metadata-%s                                                                                                                                
          interval: 1w                                                                                                                                        
                                                                                                                                                              
suggest:                                                                                                                                                      
  backends:                                                                                                                                                   
    - type: elasticsearch                                                                                                                                     
      connection:                                                                                                                                             
        clusterName: BP2                                                                                                                                      
        seeds:                                                                                                                                                
          - elasticsearchclient                                                                                                                               
        index:                                                                                                                                                
          type: rotating                                                                                                                                      
          pattern: metadata-%s                                                                                                                                
          interval: 1w  
```

I noticed now that there is a typo in the documentation for the `type` field.
I've updated the documentation in 71f6729.
