### ISSUE TITLE
Heroic node not responding over HTTP but advertising as healthy

### ISSUE THREAD

**Issue by jskelcy** [spotify/heroic#576]
I am currently running a 5 node Heroic (0.9.4) cluster in Kubernetes backed by big table and running into issues where I am seeing extream latency from the cluster. It would appear that the core issue is one of the nodes stops responding to HTTP requests, however, it advertises that it is healthy via the grpc gateway.

When running status checks via the HTTP endpoint across the entire cluster I can see all nodes other than the problematic node responding with the following (the problematic node eventually times out the request):
 `"cluster":{"onlineNodes":5,"offlineNodes":0,"ok":true}` 

Rescheduling the problematic node seems to fix the issue for some period of time until eventually, a node becomes unable to respond to HTTP traffic again and we need to restart the process. I am looking for guidance here on potential misconfiguration or debugging steps. I have some JVM metrics available to me for the cluster, however, the problematic node does not show any obvious signs of resource constraint.

**Comment by dmichel1** [comment]
Hi @jskelcy 

Internally at Spotify we have recently migrated Heroic from running on GCE vms to GKE so I can share the configuration used. It would be a good first step to compare configurations.

The JVM args are for the latest Heroic version (0.10.2) which can now run on Java 11.

If you cannot use the latest image can you share the JVM flags you are using for Java 8?

The other questions besides the configuration being used.

1. are you sending writes through the API nodes? or only query/suggest traffic?
2. do the logs say anything interesting right before the node freezes?
3. for the JVM metrics, I want to confirm that the heap isn't full/flat lining at the max? How much memory are you giving the JVM? 


heroic.yaml 
```
port: '80'
cluster:
  discovery:
    records:
    - region1._grpc
    - region2._grpc
    - region3._grpc
    type: srv
  protocols:
  - maxFrameSize: 1280010000
    port: 1494
    type: grpc
  tags:
    site: region1
  topology:
  - site: region1
  - site: region2
  - site: region3
suggest:
  backends:
  - backendType: kv
    connection:
      clusterName: heroic-suggest-region1
      index:
        pattern: heroic-suggest-region1-%s
        type: rotating
      seeds:
      - region1-heroicsuggest-master-m74s
      - region1-heroicsuggest-master-gh40
      - region1-heroicsuggest-master-446s
      sniff: true
    type: elasticsearch
metadata:
  backends:
  - backendType: kv
    connection:
      clusterName: heroic-metadata-region1
      index:
        pattern: heroic-metadata-region1-%s
        type: rotating
      seeds:
      - region1-heroicmetadata-master-rwd6
      - region1-heroicmetadata-master-0rkz
      - region1-heroicmetadata-master-tvgd
      sniff: true
    type: elasticsearch
metrics:
  aggregationLimit: 1000000
  backends:
  - credentials:
      type: default
    instance: metrics-region1
    project: google-project
    type: bigtable
  dataLimit: 20000000
  failOnLimits: 'true'
  groupLimit: 1000
  seriesLimit: 20000
analytics:
  credentials:
    type: default
  instance: analytics-region1
  project: google-project
  type: bigtable
ingestion:
  filter: 'true'
  updateMetadata: false
  updateMetrics: false
  updateSuggestions: false
shellServer:
  port: 9091
statistics:
  type: semantic
queryLogging:
  name: com.spotify.heroic.query_logging
  type: slf4j
features:
- com.spotify.heroic.sliced_data_fetch
```

JVM_ARGS
```
-XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=75 -XX:+AlwaysPreTouch
```

k8s deployment
```
    containers:
        - name: heroic
          image: $DEPLOYMENT_IMAGE
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: shell
              containerPort: 9091
              protocol: TCP
            - name: grpc
              containerPort: 1494
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 60
            failureThreshold: 3

          resources:
            requests:
              cpu: 4
              memory: 20G
            limits:
              cpu: 8
              memory: 20G
```
